"""create initial schema

Revision ID: ddfda2ba04bd
Revises:
Create Date: 2026-08-23 13:02:47.673565+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from pgvector.sqlalchemy import VECTOR
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "ddfda2ba04bd"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "evaluation_queries",
        sa.Column("query_text", sa.Text(), nullable=False),
        sa.Column("category", sa.String(length=100), nullable=False),
        sa.Column(
            "split",
            sa.Enum(
                "development",
                "test",
                name="evaluation_split",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "char_length(btrim(query_text)) > 0",
            name=op.f("ck_evaluation_queries_query_text_nonempty"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_evaluation_queries")),
    )
    op.create_table(
        "evaluation_runs",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("dataset_snapshot_sha", sa.String(length=71), nullable=False),
        sa.Column("git_commit_sha", sa.String(length=64), nullable=False),
        sa.Column(
            "method",
            sa.Enum(
                "bm25",
                "dense",
                "hybrid",
                name="retrieval_method",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "config_json",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "metrics_json",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "latency_json",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("report_path", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_evaluation_runs")),
    )
    op.create_table(
        "ingestion_runs",
        sa.Column(
            "status",
            sa.Enum(
                "running",
                "completed",
                "failed",
                name="ingestion_run_status",
                native_enum=False,
                create_constraint=True,
            ),
            server_default="running",
            nullable=False,
        ),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "discovery_queries_json",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "config_json",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("git_commit_sha", sa.String(length=64), nullable=False),
        sa.Column("discovered_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("fetched_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("unchanged_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("parsed_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("invalid_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("error_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("rate_limit_start_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("rate_limit_end_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("manifest_path", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "discovered_count >= 0 AND fetched_count >= 0 AND unchanged_count >= 0 AND parsed_count >= 0 AND invalid_count >= 0 AND error_count >= 0",
            name=op.f("ck_ingestion_runs_counts_nonnegative"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ingestion_runs")),
    )
    op.create_table(
        "repositories",
        sa.Column("github_repository_id", sa.BigInteger(), nullable=False),
        sa.Column("owner", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("full_name", sa.String(length=512), nullable=False),
        sa.Column("html_url", sa.Text(), nullable=False),
        sa.Column("default_branch", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("stars_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("forks_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("open_issues_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("is_fork", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("is_archived", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("license_spdx_id", sa.String(length=255), nullable=True),
        sa.Column("license_name", sa.String(length=255), nullable=True),
        sa.Column(
            "license_status",
            sa.Enum(
                "permissive",
                "restrictive",
                "missing",
                "unknown",
                name="license_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("pushed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "fetched_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("etag", sa.String(length=255), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "stars_count >= 0 AND forks_count >= 0 AND open_issues_count >= 0",
            name=op.f("ck_repositories_counts_nonnegative"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_repositories")),
        sa.UniqueConstraint("full_name", name=op.f("uq_repositories_full_name")),
        sa.UniqueConstraint(
            "github_repository_id", name=op.f("uq_repositories_github_repository_id")
        ),
    )
    op.create_table(
        "ingestion_run_items",
        sa.Column("ingestion_run_id", sa.UUID(), nullable=False),
        sa.Column("repository_full_name", sa.String(length=512), nullable=False),
        sa.Column("path", sa.Text(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "ingested",
                "unchanged",
                "skipped",
                "invalid",
                "error",
                name="ingestion_item_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("content_sha256", sa.String(length=64), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "content_sha256 IS NULL OR char_length(content_sha256) = 64",
            name=op.f("ck_ingestion_run_items_content_sha256_length"),
        ),
        sa.CheckConstraint(
            "duration_ms IS NULL OR duration_ms >= 0",
            name=op.f("ck_ingestion_run_items_duration_ms_nonnegative"),
        ),
        sa.ForeignKeyConstraint(
            ["ingestion_run_id"],
            ["ingestion_runs.id"],
            name=op.f("fk_ingestion_run_items_ingestion_run_id_ingestion_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ingestion_run_items")),
        sa.UniqueConstraint(
            "ingestion_run_id",
            "repository_full_name",
            "path",
            name=op.f("uq_ingestion_run_items_ingestion_run_id_repository_full_name_path"),
        ),
    )
    op.create_table(
        "skills",
        sa.Column("repository_id", sa.UUID(), nullable=False),
        sa.Column("path", sa.Text(), nullable=False),
        sa.Column("html_url", sa.Text(), nullable=False),
        sa.Column("raw_url", sa.Text(), nullable=True),
        sa.Column("git_blob_sha", sa.String(length=64), nullable=False),
        sa.Column("content_sha256", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("description", sa.String(length=1024), nullable=False),
        sa.Column("declared_license", sa.String(length=255), nullable=True),
        sa.Column("compatibility", sa.Text(), nullable=True),
        sa.Column(
            "allowed_tools",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "metadata_json",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "extension_fields_json",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("body_text", sa.Text(), nullable=False),
        sa.Column("search_text", sa.Text(), nullable=False),
        sa.Column("safe_snippet", sa.Text(), nullable=False),
        sa.Column("embedding", VECTOR(384), nullable=True),
        sa.Column(
            "validation_status",
            sa.Enum(
                "valid",
                "warning",
                "invalid",
                name="validation_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "validation_messages_json",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column("has_scripts", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("has_references", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("has_assets", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("script_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("reference_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("asset_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("heading_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("code_block_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("external_link_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("word_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("byte_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "first_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "last_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("indexed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "char_length(content_sha256) = 64", name=op.f("ck_skills_content_sha256_length")
        ),
        sa.CheckConstraint(
            "script_count >= 0 AND reference_count >= 0 AND asset_count >= 0 AND heading_count >= 0 AND code_block_count >= 0 AND external_link_count >= 0 AND word_count >= 0 AND byte_count >= 0",
            name=op.f("ck_skills_counts_nonnegative"),
        ),
        sa.ForeignKeyConstraint(
            ["repository_id"],
            ["repositories.id"],
            name=op.f("fk_skills_repository_id_repositories"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_skills")),
        sa.UniqueConstraint("repository_id", "path", name=op.f("uq_skills_repository_id_path")),
    )
    op.create_table(
        "qrels",
        sa.Column("query_id", sa.UUID(), nullable=False),
        sa.Column("skill_id", sa.UUID(), nullable=False),
        sa.Column("relevance", sa.SmallInteger(), nullable=False),
        sa.Column("rationale", sa.Text(), nullable=True),
        sa.Column(
            "labelled_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.CheckConstraint("relevance BETWEEN 0 AND 2", name=op.f("ck_qrels_relevance_range")),
        sa.ForeignKeyConstraint(
            ["query_id"],
            ["evaluation_queries.id"],
            name=op.f("fk_qrels_query_id_evaluation_queries"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["skill_id"], ["skills.id"], name=op.f("fk_qrels_skill_id_skills"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_qrels")),
        sa.UniqueConstraint("query_id", "skill_id", name=op.f("uq_qrels_query_id_skill_id")),
    )
    op.create_table(
        "skill_files",
        sa.Column("skill_id", sa.UUID(), nullable=False),
        sa.Column("relative_path", sa.Text(), nullable=False),
        sa.Column(
            "file_type",
            sa.Enum(
                "script",
                "reference",
                "asset",
                "other",
                name="supporting_file_type",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("git_blob_sha", sa.String(length=64), nullable=False),
        sa.Column("extension", sa.String(length=32), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.CheckConstraint("size_bytes >= 0", name=op.f("ck_skill_files_size_bytes_nonnegative")),
        sa.ForeignKeyConstraint(
            ["skill_id"],
            ["skills.id"],
            name=op.f("fk_skill_files_skill_id_skills"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_skill_files")),
        sa.UniqueConstraint(
            "skill_id", "relative_path", name=op.f("uq_skill_files_skill_id_relative_path")
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("skill_files")
    op.drop_table("qrels")
    op.drop_table("skills")
    op.drop_table("ingestion_run_items")
    op.drop_table("repositories")
    op.drop_table("ingestion_runs")
    op.drop_table("evaluation_runs")
    op.drop_table("evaluation_queries")
    # ### end Alembic commands ###
    op.execute("DROP EXTENSION IF EXISTS vector")
